### ISSUE TITLE
Pair Devices

### ISSUE THREAD

**Issue by ospectreo** [Maxmudjon/com.maxmudjon.mihomey#1]
Can you write a manual how to connect devices to homey please?
when I select a device from the list, then in the next window "Follow the instructions" in a second I get the message "No devices found. You may close this window."

**Comment by Maxmudjon** [comment]
![mihomey wallpaper long](https://user-images.githubusercontent.com/23142922/49240453-fe77d180-f426-11e8-9962-17842c532710.png)

**Comment by Maxmudjon** [comment]
Athom Homey plugin: add interoperability with Mi / Aqara zigbee devices connected via Mijia Gateway v2.

**Comment by ospectreo** [comment]
Спасибо. Я уже разобрался. Почему ты эту апликацию не выложишь в атом маркет на их сайт? Работает идеально. Я уже год пытаюсь подсоединить с той програмой для xiaomi zigbee что у них опубликована. Вообще ничего подключить не мог.

**Comment by Maxmudjon** [comment]
потом буду опубликовать на Homey App Store.

**Comment by ospectreo** [comment]
Единственная проблема что у меня осталась:
Я пробросил все датчики и кнопки через Sprut Homekit в Дом на IOS
В колобке я могу настроить правила на нажатие любой кнопки а в программе Дом те же кнопки пишется что они не поддерживаются
Хотя при работе тех же кнопок через HomeBridge (на малине) в IOS я мог создавать автоматизацию на одно двойное или длинное нажатие
