### ISSUE TITLE
On/Off usb in flows for Mi Smart Plug WiFi With 2 USB

### ISSUE THREAD

**Issue by Flesh192** [Maxmudjon/com.maxmudjon.mihomey#10]
Now its not possible to use in flows on/off usb in Mi Smart Plug WiFi With 2 USB device.
Is it possible to add this functionality?

**Comment by Flesh192** [comment]
Please review and merge, if everything ok
https://github.com/Maxmudjon/com.maxmudjon.mihomey/pull/11

**Comment by Maxmudjon** [comment]
Thanks for the support, I added your change request.
