### ISSUE TITLE
Невозможно добавить устройства

### ISSUE THREAD

**Issue by mike02spb** [Maxmudjon/com.maxmudjon.mihomey#2]
Махмуджон, здравствуйте! 
Подскажите, в чем может быть проблема при добавлении устройств (выключателей, гирконов и кубика) в колобок? Вылезает такая ошибка:
An unkown error has occured [unknown_error]
Спасибо!

**Comment by Maxmudjon** [comment]
Здравствуйте

**Comment by mike02spb** [comment]
Это при добавлении любого устройства через ваш плане (в окне добавления)

**Comment by Maxmudjon** [comment]
проблема уже решено ?

**Comment by mike02spb** [comment]
Нет, к сожалению не решена.
Добавил их через другой плагин. 
Единственное, я подумал, что это может быть из-за отсутствия МиХаба

**Comment by Maxmudjon** [comment]
Этот плагин через Mi Hub работает. без него никак)

**Comment by mike02spb** [comment]
Значит, сам тупанул)) извините! 
Но, в связи с приобретением МиХаба на выходных испробую Ваш плагин. Надеюсь, смогу кубиком пользоваться тогда. 
Кстати, не знаете, почему пылесос в вашем плагине может отваливаться, при том, что в другом колобок в это же время его видит?

**Comment by mike02spb** [comment]
И еще, извините за вопрос не в тему, не знаете почему никак не заставить работать плагин ХоумКит спрута, при том, что колобковский экспериментальный работает? 
К сожалению, ни в чате, ни Спрут мне не ответили

**Comment by Maxmudjon** [comment]
В плагине кубик работает (mi, aqara)

**Comment by Maxmudjon** [comment]
> Кстати, не знаете, почему пылесос в вашем плагине может отваливаться, при том, что в другом колобок в это же время его видит?
лог или ошибка есть ?

**Comment by mike02spb** [comment]
А где можно посмотреть логи или ошибки эти? 
Доступ в developer.athom у меня есть
