### ISSUE TITLE
App can't detect my Aqara D1 double switch (2018)

### ISSUE THREAD

**Issue by amoinier** [Maxmudjon/com.maxmudjon.mihomey#22]
Hi!

I have a double switch aqara connected to my gateway but when I want to add it on Homey, it didn't appear.

**Comment by Maxmudjon** [comment]
@amoinier model WXKG07LM ?

**Comment by Maxmudjon** [comment]
@amoinier please try 1.1.8 version

**Comment by amoinier** [comment]
Yes, it's a WXKG07LM model. I'm on Mainland China for my gateway, It change anything ?

**Comment by amoinier** [comment]
Wow, It works ! You are a king ;)

I have an another question. What's the difference with your other app for mihome (https://homey.app/fr-fr/app/com.xiaomi-miio/Xiaomi-Mi-Home/) ?

**Comment by Maxmudjon** [comment]
> Wow, It works ! You are a king ;)
> 
> I have an another question. What's the difference with your other app for mihome (https://homey.app/fr-fr/app/com.xiaomi-miio/Xiaomi-Mi-Home/) ?

I'll add there later
