### ISSUE TITLE
[suggestion] Replace miio module with node-mihome

### ISSUE THREAD

**Issue by Amelsfort** [Maxmudjon/com.maxmudjon.mihomey#25]
While searching for my issue adding the air purifier v7, I came across this node module: https://github.com/maxinminax/node-mihome
It's a fork of the miio module, but this one is more up-to-date. Maybe this module can be used instead of miio to support newer devices.

**Comment by Maxmudjon** [comment]
@Amelsfort  thanks for the suggestions ok i will migrate to node-mihome
