### ISSUE TITLE
Homey Community Store

### ISSUE THREAD

**Issue by drigga1512** [Maxmudjon/com.maxmudjon.mihomey#28]
Hello,

since your App has been rejected by Athom, you can upload it to https://store.homey.community/
There are several apps, which have been rejected by Athom.

**Comment by shaarkys** [comment]
https://store.homey.community/app/com.maxmudjon.mihomey

**Comment by drigga1512** [comment]
Tks, didn‘t see that ut‘s already there.

Tks
