### ISSUE TITLE
homey App Store

### ISSUE THREAD

**Issue by maikburd** [Maxmudjon/com.maxmudjon.mihomey#3]
Hello, thanks for this great work. I wonder why the app is not in the Homey App Store. Is this still planned?

**Comment by Maxmudjon** [comment]
I will add soon

**Comment by powermarcel10** [comment]
Hello, I would that I had seen this app earlier.. Why is it not in the playstore??

**Comment by Maxmudjon** [comment]
@jghaanstra  and I will agree on the reasons for merging our plugins, I am preparing the plugin for the party, there isn’t left)
