### ISSUE TITLE
Add device Mi Air Purifier 3H

### ISSUE THREAD

**Issue by corvdniet** [Maxmudjon/com.maxmudjon.mihomey#30]
Is it possible to add the Mi Air Purifier 3H?
It would be very appriciated

**Comment by thecesco** [comment]
I'm interested in the same model too. Dev could you please add it?

**Comment by Maxmudjon** [comment]
@corvdniet @thecesco please write me on telegram [https://t.me/payziyev](https://t.me/payziyev)

**Comment by corvdniet** [comment]
Don't know how to do that without a phone number. Sorry hardly any experience with telegram.

**Comment by Airwolf33** [comment]
3H added in the last version, but I can't add it...

**Comment by Airwolf33** [comment]
Air Purifier 3H do not work in v1.1.11, can't add it in homey

**Comment by corvdniet** [comment]
Same here ... can't add the AirPurifier 3H

**Comment by corvdniet** [comment]
Latest version (1.1.12) works with Air Purifier 3H. Thanks
