### ISSUE TITLE
Xiaomi Smartmi Evaporative Humidifier 2

### ISSUE THREAD

**Issue by jahnkenneth** [Maxmudjon/com.maxmudjon.mihomey#32]
Hello,

is it possible to add support for Xiaomi Smartmi Evaporative Humidifier 2?

![DD9FCCA7-7D44-4AC8-ACD1-7D60EAA87F5E](https://user-images.githubusercontent.com/28279147/103115743-181a9000-4664-11eb-90ed-98bc6dcd2d66.jpeg)

**Comment by tes-com** [comment]
Please add this one. i really need it.

**Comment by Maxmudjon** [comment]
added!
