### ISSUE TITLE
Smartmi EvaPorative Humidifier 2

### ISSUE THREAD

**Issue by tes-com** [Maxmudjon/com.maxmudjon.mihomey#33]
Hello

When i add the Smartmi Evaporative Humidifier to Homey (in the Xiaomi Mi Home app version v3.0.8 (In dutch Mi Luchtbevochtiger v2) i get the error message "Device.power is not a function"

Homey is running firmware 5.0.0-rc.50

I used the # Xiaomi Cloud Tokens Extractor to get the token and ip adress

Please can you help me ?

**Comment by PeetersJan** [comment]
Perfectly normal since it seems as if it isn't supported (yet).

**Comment by Maxmudjon** [comment]
added!
