### ISSUE TITLE
Support request: Mi Smart Standing Fan 3

### ISSUE THREAD

**Issue by basvdploeg** [Maxmudjon/com.maxmudjon.mihomey#41]
Support request for the Smartmi Standing Fan 3
 Model: zhimi.fan.za5

**Comment by andrekrit** [comment]
Yes please, I second the support request for the Smartmi Standing Fan 3. I even looked at the code to see how easy it would be to add it myself, but I'm not a Javascript / Node.js kinda guy. Still not sure why Homey went that route... sigh. Developing it in Python would've made more sense, but that's my opinion. I see they already have support for all the Smartmi fans in Home Assistant: https://github.com/syssi/xiaomi_fan.

**Comment by Maxmudjon** [comment]
added
