### ISSUE TITLE
Wrong Password Format

### ISSUE THREAD

**Issue by erlandjack** [Maxmudjon/com.maxmudjon.mihomey#5]
I can't connect my gateway because of the password doesn't correspond to what is in the instruction (0123456789ABCDEF). Spent giant many hours to generate new password but never succeeded. In addition to the numbers I never get capital letters, and always more than "abscdef", as well as "iyux88mr9bn4y2af" or "or3n7nt34a2fqhop" etc.
Will there be support for such passwords or I have no chance?

**Comment by Maxmudjon** [comment]
0.4.0 (07.06.2019)
Added a new feature for android users: the password that is generated in the plugin in capital letters is now saved to the gateway.

**Comment by erlandjack** [comment]
Thank you very much.
