### ISSUE TITLE
Not able to add devices

### ISSUE THREAD

**Issue by jahnkenneth** [Maxmudjon/com.maxmudjon.mihomey#50]
My Mi bridge is paired to Homey, but when trying to add devices no devices are found. 

What could be the cause of this?

**Comment by frekel** [comment]
@jahnkenneth Can you tell me how you fixed adding the devices?

**Comment by jahnkenneth** [comment]
> @jahnkenneth Can you tell me how you fixed adding the devices?

I did not. Just quit using the app.

**Comment by frekel** [comment]
Thanks for your quick answer!! :+1:
