### ISSUE TITLE
Ikea bulbs

### ISSUE THREAD

**Issue by maikburd** [Maxmudjon/com.maxmudjon.mihomey#6]
Hi, Can you add the Ikea bulbs?

![564B4B05-D373-4C35-BFB1-1A16B55680C1](https://user-images.githubusercontent.com/4597806/62413492-bf31fe00-b60f-11e9-9ff2-18e9bcf28a6a.png)
![E9994A66-52A7-4859-826F-8E105CE4CEB9](https://user-images.githubusercontent.com/4597806/62413493-bf31fe00-b60f-11e9-9758-b62ba25a7815.jpeg)

**Comment by Maxmudjon** [comment]
Hi you have telegram messanger ?

> Hi, Can you add the Ikea bulbs?
> 
> ![564B4B05-D373-4C35-BFB1-1A16B55680C1](https://user-images.githubusercontent.com/4597806/62413492-bf31fe00-b60f-11e9-9ff2-18e9bcf28a6a.png)
> ![E9994A66-52A7-4859-826F-8E105CE4CEB9](https://user-images.githubusercontent.com/4597806/62413493-bf31fe00-b60f-11e9-9758-b62ba25a7815.jpeg)

Hi you have telegram messenger

**Comment by maikburd** [comment]
Yes, i have Telegramm. I have sent you a message.

**Comment by Maxmudjon** [comment]
> Yes, i have Telegramm. I have sent you a message.
write me to https://t.me/payziyev
