### ISSUE TITLE
Migration to SDK3 in the future?

### ISSUE THREAD

**Issue by frekel** [Maxmudjon/com.maxmudjon.mihomey#63]
Hi,

I want to use your app because my Zigbee on my Homey is not working as expected. I want to add the Xiaomi hub so I can take a couple of sensors off Homey.

Now I understand you app it the one I need, but it is a SKDv2 only app. Are there any plans to migrate the app to the SDKv3?

(I can understand that your answer shall be *NO*, but I just want to have some security ;) )

**Comment by frekel** [comment]
Nevermind. I now know that Homey is backward compatible with SDK2 apps. I installed the app perfectly!

**Comment by HenkRenting** [comment]
Unluckily this is not the case for the new Homey Pro 2023 anymore. An update to SDK3 is mandatory for an app on Homey Pro 2023.
