### ISSUE TITLE
Tutorial for get password

### ISSUE THREAD

**Issue by KrakenTyio** [Maxmudjon/com.maxmudjon.mihomey#7]
From your tutorial to get password its hard/imposible to optain password

Im from region Slovakia and in Mi Home 5.6.13 are not hidden menu for password.

When i switch to Chinese mainline ill lost all my local pair devices.

**Comment by KrakenTyio** [comment]
When i set IP and token(have token from pass version of Mi Home) to generate new password, i get error with Object [Object] message

**Comment by Maxmudjon** [comment]
> When i set IP and token(have token from pass version of Mi Home) to generate new password, i get error with Object [Object] message

Try installing a new version

**Comment by Maxmudjon** [comment]
### **Add gateway using MAC and password:**
![MAC_PASSWORD](https://user-images.githubusercontent.com/23142922/71758248-286bb500-2ebf-11ea-9c05-e01d8f89c56d.gif)

### **Add gateway using IP and Token:**
![IP_TOKEN_GENERATE](https://user-images.githubusercontent.com/23142922/71758263-40433900-2ebf-11ea-909d-eb7a19a3c3d8.gif)
