### ISSUE TITLE
Support for Aqara Wireless Remote Switches (Single Rocker)

### ISSUE THREAD

**Issue by xsola** [Maxmudjon/com.maxmudjon.mihomey#8]
Hi! 

First of all, thanks for this great app.!

I've got two Aqara Wireless Remote Switches (Single Rocker). I tried to add these in Homey, but unfortunately they are not recognized. 
Is it possible to add support for these items? 

I tried all other Aqara Wireless Remote options, but it is really not recognized. 

According to the Xiaomi app it is model lumi.remote.b186acn01

Thanks in advance. And please let me know if and when I need to test things.

 Best, Axel

**Comment by Maxmudjon** [comment]
@xsola hi, thanks, ok i will add this model as Single Switch Advanced
